mysql:
  dsn: root:root@tcp(10.21.32.154:3306)/nft-go?charset=utf8mb4&parseTime=True&loc=Local
redis:
  address: 10.21.32.221:6379
  password: 123456
key: rawven
rocketmq:
  group: testGroup
  nameserver: 10.21.32.221:9876
